# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# 针对 document-picker 相关 pod 禁用 modular headers
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.include?('document-picker') || pod.name.include?('DocumentPicker')
      # 强制使用静态库而非模块
      def pod.build_type
        Pod::BuildType.new(linkage: :static, linkage_options: {})
      end
    end
  end
end

target 'cashbook_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # 针对 document-picker 相关 pod 禁用 DEFINES_MODULE
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name.include?('document-picker') || target.name.include?('DocumentPicker')
          config.build_settings['DEFINES_MODULE'] = 'NO'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        end
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
